#if !defined(__GNUC__) || defined(__clang__)
	#if defined(__EMSCRIPTEN__)
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with Emcc. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#elif defined(__clang__)
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with Clang. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#elif defined(_MSC_VER)
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with Msvc. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#else
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with some other compiler. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#endif
#endif


/*
BEGIN-TIGRESS
{
  "Tigress": {
    "Source": "This file was generated by Tigress, a product of the University of Arizona.",
    "Author": "Christian Collberg",
    "Contact": "collberg@gmail.com",
    "Version": "4.0.11,Operating system=Linux, Architecture=x86_64, Git hash=b27316009b56c6a9243055163d440e9ae74b2991, Date=2025-07-23T23:33:20:+0000",
    "Url": "https://tigress.wtf"
  },
  "Usage": {
    "Research": "Tigress is free to use for research purposes.",
    "Commercial": "Any use in a commercial setting requires a license from the University of Arizona."
  }
}
END-TIGRESS
*/


/*
BEGIN-CONFIG
[
  {
    "Environment": {
      "architecture": "x86",
      "wordsize": "64",
      "os": "Linux",
      "compiler": "Gcc",
      "compilerVersion": "(1,0)"
    }
  },
  {
    "Major version number": -1,
    "Minor version number": -1,
    "gcc version string": "Unknown",
    "If assembly names have leading underscore": false,
    "Size of 'short'": 2,
    "Size of 'int'": 4,
    "Size of '_Bool'": 1,
    "Size of 'long'": 8,
    "Size of 'long long'": 8,
    "Size of pointers": 8,
    "Size of 'float'": 4,
    "Size of '_Float32x'": 8,
    "Size of '_Float64x'": 16,
    "Size of 'double'": 8,
    "Size of 'long double'": 16,
    "Size of '_Float16'": 0,
    "Size of '_Float128'": 16,
    "Size of 'float _Complex'": 8,
    "Size of 'double _Complex'": 16,
    "Size of 'long double _Complex'": 32,
    "Size of '_Float128 _Complex'": 0,
    "Size of 'void'": 1,
    "Size of function": 8,
    "Type of 'sizeof(T)'": "unsigned long",
    "Type of 'wchar_t'": "int",
    "Type of 'char16_t'": "unsigned short",
    "Type of 'char32_t'": "unsigned int",
    "Alignment of 'short'": 2,
    "Alignment of 'int'": 4,
    "Alignment of '_Bool'": 1,
    "Alignment of 'long'": 8,
    "Alignment of 'long long'": 8,
    "Alignment of pointers": 8,
    "Alignment of enum types": 4,
    "Alignment of 'float'": 4,
    "Alignment of '_Float32x'": 8,
    "Alignment of '_Float64x'": 16,
    "Alignment of 'double'": 8,
    "Alignment of 'long double'": 16,
    "Alignment of '_Float16'": 0,
    "Alignment of '_Float128'": 16,
    "Alignment of 'float _Complex'": 4,
    "Alignment of 'double _Complex'": 8,
    "Alignment of 'long double _Complex'": 16,
    "Alignment of '_Float128 _Complex'": 0,
    "Alignment of strings": 1,
    "Alignment of function": 1,
    "Alignment of anything with the 'aligned' attribute": 16,
    "Whether 'char' is unsigned": false,
    "whether the machine is little endian": true,
    "whether __thread is a keyword": true,
    "whether __builtin_va_list is builtin (gccism)": true
  },
  {
    "C language specification": "C99",
    "Generate code for Microsoct MSVC": false,
    "Whether to convert local static variables into global static variables": false,
    "Whether to use the logical operands LAnd and LOr": false,
    "Whether to use GCC's computed gotos": true,
    "Whether to expand ranges of values in case statements": false
  },
  {
    "Bitsize of char": 8,
    "Bitsize of signed char": 8,
    "Bitsize of unsigned char": 8,
    "Bitsize of _Bool": 8,
    "Bitsize of short": 16,
    "Bitsize of unsigned short": 16,
    "Bitsize of int": 32,
    "Bitsize of unsigned int": 32,
    "Bitsize of long": 64,
    "Bitsize of unsigned long": 64,
    "Bitsize of long long": 64,
    "Bitsize of unsigned long long": 64,
    "Bitsize of __int128": 128,
    "Bitsize of unsigned __int128": 128,
    "Bitsize of float": 32,
    "Bitsize of double": 64,
    "Bitsize of long double": 128,
    "Bitsize of float16": 0,
    "Bitsize of float128": 128,
    "Bitsize of float _Complex": 64,
    "Bitsize of double _Complex": 128,
    "Bitsize of long double _Complex": 256,
    "Bitsize of _float128 _Complex": 0
  }
]
END-CONFIG
*/


/*
BEGIN-OPTIONS
[
  {
    "task": 1,
    "kind": "EncodeArithmetic",
    "prefix": "",
    "seed": "",
    "funSpec": [ [ "id(quick_sort)", "" ] ],
    "globalVarSpec": [],
    "localVarSpec": [],
    "exclude": [],
    "funs": [ "quick_sort" ],
    "options": {
      "common": {
        "prefix": "",
        "verbosity": "None",
        "statistics": "None",
        "transformationKind": "Ident",
        "vlaTransformation": "alloca",
        "transformationNumber": "0"
      },
      "kinds": [ "builtin" ],
      "maxLevel": "1",
      "maxTransformations": "1",
      "implicitFlowOptions": {
        "common": {
          "prefix": "",
          "verbosity": "None",
          "statistics": "None",
          "transformationKind": "Ident",
          "vlaTransformation": "alloca",
          "transformationNumber": "0"
        },
        "handlerCount": "1",
        "jitCount": "1",
        "jitFunctionBody": "(for (for (for (for (if (bb 2) (bb 2))))))",
        "kinds": [ "counter_int" ],
        "combiner": "*",
        "trainingKind": "gap",
        "time": "false",
        "trace": "false",
        "train": "false",
        "trainingTimesClock": "0",
        "trainingTimesThread": "0",
        "trainingMaxFailureRateClock": "5",
        "trainingMaxFailureRateThread": "1",
        "trainingMinGap": "80",
        "trainingData": "None",
        "trainingConfidenceLevel": "0.95",
        "trainingTargetErrorRate": "0.0001",
        "trainingParameterRange": [
          "(trivial_clock,(1,10000))", "(trivial_thread_1,(1,10000))",
          "(trivial_thread_2,(1,10000))", "(trivial_counter,(1,10000))",
          "(file_cache_time,(1,1024))", "(file_cache_thread_1,(1,1024))",
          "(file_cache_thread_2,(1,1024))",
          "(file_cache_thread_timer,(1,1024))", "(mem_cache_time,(2,64))",
          "(mem_cache_thread_1,(2,64))", "(mem_cache_thread_2,(2,64))",
          "(jit_time,(0,0))", "(jit_thread_1,(0,0))", "(jit_thread_2,(0,0))",
          "(jit_thread_timer,(0,0))", "(branchPrediction_time,(2,10))"
        ]
      },
      "maxSplit": "0",
      "repeatTimes": "1",
      "addOpaques": "false",
      "addImplicitFlow": "false"
    }
  }
]
END-OPTIONS
*/


/*
BEGIN-UNIVERSE
{
  "Not added to universe": [
    "__sync_fetch_and_xor_2", "__sync_nand_and_fetch_1",
    "__sync_and_and_fetch", "__sync_val_compare_and_swap_16",
    "__atomic_or_fetch", "__sync_sub_and_fetch_1", "__atomic_fetch_and",
    "__atomic_xor_fetch_16", "__atomic_fetch_nand_16",
    "__sync_add_and_fetch_4", "__sync_and_and_fetch_8",
    "__sync_fetch_and_add_2", "__sync_synchronize", "__sync_or_and_fetch",
    "__atomic_xor_fetch_8", "__atomic_xor_fetch_2", "__sync_fetch_and_and_8",
    "__atomic_store_16", "__atomic_fetch_and_8", "__sync_sub_and_fetch_2",
    "__atomic_and_fetch_2", "__atomic_fetch_add_8",
    "__c11_atomic_thread_fence", "__atomic_fetch_nand", "__atomic_store",
    "__atomic_add_fetch_2", "__sync_fetch_and_or_2", "__sync_sub_and_fetch",
    "__sync_fetch_and_add_1", "__sync_and_and_fetch_1",
    "__atomic_nand_fetch_16", "__sync_val_compare_and_swap_8",
    "__sync_xor_and_fetch_1", "__atomic_fetch_xor_8",
    "__sync_or_and_fetch_2", "__sync_fetch_and_sub_16",
    "__atomic_exchange_1", "__sync_fetch_and_and_2", "__sync_fetch_and_and",
    "__atomic_feraiseexcept", "__atomic_and_fetch_4", "__atomic_or_fetch_4",
    "__sync_xor_and_fetch_2", "__sync_swap_2", "__atomic_fetch_and_2",
    "__sync_val_compare_and_swap_4", "__sync_lock_release", "__sync_swap",
    "__atomic_fetch_nand_8", "__sync_fetch_and_add_4",
    "__atomic_fetch_nand_2", "__atomic_load_n", "__atomic_exchange_n",
    "__atomic_fetch_or_8", "__sync_lock_release_4", "__sync_fetch_and_max",
    "__atomic_fetch_or_4", "__atomic_load_2", "__atomic_fetch_sub_4",
    "__atomic_compare_exchange_1", "__sync_fetch_and_sub_2", "__atomic_load",
    "__atomic_or_fetch_16", "__atomic_add_fetch_16", "__sync_lock_release_1",
    "__atomic_fetch_add_16", "__sync_fetch_and_and_1",
    "__atomic_compare_exchange_2", "__sync_and_and_fetch_16",
    "__atomic_exchange", "__atomic_sub_fetch_2", "__atomic_fetch_xor_16",
    "__sync_xor_and_fetch_4", "__atomic_fetch_or_16", "__atomic_load_4",
    "__sync_fetch_and_sub_1", "__atomic_store_n", "__sync_fetch_and_sub_8",
    "__sync_fetch_and_or_16", "__sync_lock_test_and_set",
    "__atomic_fetch_and_16", "__sync_lock_test_and_set_2",
    "__atomic_nand_fetch", "__atomic_load_8", "__atomic_xor_fetch_4",
    "__atomic_fetch_sub_2", "__sync_fetch_and_xor_4",
    "__sync_fetch_and_or_1", "__atomic_store_8", "__sync_nand_and_fetch_4",
    "__atomic_or_fetch_2", "__atomic_fetch_xor", "__sync_add_and_fetch_8",
    "__atomic_fetch_xor_4", "__sync_bool_compare_and_swap",
    "__sync_fetch_and_xor_16", "__atomic_and_fetch_1",
    "__sync_lock_release_2", "__atomic_xor_fetch_1",
    "__sync_xor_and_fetch_8", "__warn_memset_zero_len",
    "__sync_fetch_and_xor_8", "__sync_fetch_and_sub", "__atomic_fetch_add_2",
    "__sync_swap_1", "__sync_fetch_and_xor_1", "__sync_fetch_and_add_16",
    "__sync_fetch_and_umin", "__atomic_fetch_sub", "__sync_fetch_and_nand_4",
    "__sync_add_and_fetch_2", "__c11_atomic_signal_fence",
    "__atomic_add_fetch_4", "__sync_fetch_and_min", "__sync_swap_8",
    "__sync_fetch_and_or", "__sync_sub_and_fetch_4",
    "__sync_lock_test_and_set_4", "__sync_or_and_fetch_8",
    "__sync_lock_release_16", "__sync_fetch_and_or_4",
    "__atomic_nand_fetch_8", "__atomic_sub_fetch_1", "__atomic_fetch_or",
    "__sync_fetch_and_nand_16", "__atomic_nand_fetch_4",
    "__sync_lock_release_8", "__sync_bool_compare_and_swap_1",
    "__atomic_sub_fetch_4", "__atomic_compare_exchange_n",
    "__sync_add_and_fetch", "__atomic_signal_fence", "__atomic_fetch_nand_1",
    "__atomic_and_fetch_16", "__sync_fetch_and_nand",
    "__atomic_thread_fence", "__sync_swap_4", "__atomic_test_and_set",
    "__sync_fetch_and_sub_4", "__atomic_exchange_16", "__xray_customevent",
    "__atomic_clear", "__atomic_fetch_xor_1", "__atomic_and_fetch",
    "__atomic_compare_exchange_4", "__sync_fetch_and_add_8",
    "__sync_or_and_fetch_16", "__sync_nand_and_fetch", "__atomic_load_16",
    "__atomic_always_lock_free", "__sync_xor_and_fetch",
    "__atomic_exchange_8", "__sync_xor_and_fetch_16", "__atomic_or_fetch_8",
    "__sync_add_and_fetch_1", "__sync_bool_compare_and_swap_2",
    "__atomic_or_fetch_1", "__sync_fetch_and_nand_8", "__atomic_fetch_add",
    "__atomic_nand_fetch_1", "__sync_bool_compare_and_swap_16",
    "__atomic_compare_exchange_16", "__atomic_fetch_or_1",
    "__atomic_fetch_add_1", "__c11_atomic_is_lock_free", "__xray_typedevent",
    "__sync_swap_16", "__atomic_fetch_sub_1", "__atomic_store_2",
    "__sync_sub_and_fetch_16", "__sync_fetch_and_nand_1",
    "__atomic_exchange_4", "__sync_fetch_and_nand_2",
    "__sync_nand_and_fetch_2", "__sync_fetch_and_xor",
    "__atomic_fetch_and_4", "__sync_or_and_fetch_1",
    "__atomic_compare_exchange", "__sync_or_and_fetch_4",
    "__sync_lock_test_and_set_16", "__atomic_load_1",
    "__sync_bool_compare_and_swap_8", "__atomic_fetch_xor_2",
    "__sync_val_compare_and_swap", "__atomic_store_4",
    "__atomic_fetch_and_1", "__atomic_fetch_nand_4",
    "__sync_sub_and_fetch_8", "__atomic_sub_fetch_8",
    "__atomic_fetch_sub_16", "__sync_bool_compare_and_swap_4",
    "__sync_val_compare_and_swap_2", "__sync_and_and_fetch_4",
    "__sync_lock_test_and_set_8", "__atomic_exchange_2",
    "__sync_fetch_and_or_8", "__sync_nand_and_fetch_16",
    "__atomic_fetch_add_4", "__atomic_nand_fetch_2", "__atomic_sub_fetch",
    "__sync_lock_test_and_set_1", "__atomic_compare_exchange_8",
    "__atomic_add_fetch", "__atomic_xor_fetch", "__sync_fetch_and_add",
    "__sync_and_and_fetch_2", "__atomic_add_fetch_1", "__atomic_add_fetch_8",
    "__sync_fetch_and_and_4", "__atomic_fetch_sub_8",
    "__sync_fetch_and_and_16", "__sync_val_compare_and_swap_1",
    "__atomic_store_1", "__atomic_fetch_or_2", "__atomic_sub_fetch_16",
    "__sync_add_and_fetch_16", "__sync_nand_and_fetch_8",
    "__atomic_is_lock_free", "__sync_fetch_and_umax", "__atomic_and_fetch_8"
  ],
  "Transformations": [
    {
      "TransformationNumber": 200,
      "TransformationKind": "PlatformFixes",
      "TransformationUpdates": {}
    },
    {
      "TransformationNumber": 1,
      "TransformationKind": "EncodeArithmetic",
      "TransformationUpdates": {
        "Modified Function Implementations": [ "quick_sort" ]
      }
    },
    {
      "TransformationNumber": 0,
      "TransformationKind": "Initialize",
      "TransformationUpdates": {
        "Modified Function Implementations": [ "main" ],
        "New Global Variables": {
          "_TIG_IZ_6cmB_envp": "INIT_FUN: '_TIG_IZ_6cmB_envp__INIT'",
          "_TIG_IZ_6cmB_argv": "INIT_FUN: '_TIG_IZ_6cmB_argv__INIT'",
          "_TIG_IZ_6cmB_argc": "INIT_FUN: '_TIG_IZ_6cmB_argc__INIT'"
        }
      }
    },
    {
      "TransformationNumber": -1,
      "TransformationKind": "Initialize",
      "TransformationUpdates": {
        "New Functions": [ "main", "quick_sort" ],
        "New Externs": [
          "__builtin_catanhf", "__builtin_ia32_psrawi",
          "__builtin_rotateright8", "__builtin_fdimf128", "__builtin_log1pf",
          "__builtin_ia32_vec_init_v4hi", "__builtin_isless",
          "__builtin_ia32_paddsw", "__builtin_snprintf",
          "__builtin_ia32_psubd", "__builtin_fmaxf",
          "__builtin_ia32_unpckhps", "__builtin_acos",
          "__builtin_ssubl_overflow", "__builtin___sprintf_chk",
          "__builtin_lgammaf", "__builtin_assume_aligned",
          "__builtin_stpncpy", "__builtin_signbitl", "__builtin_lround",
          "__builtin_rotateleft32", "__builtin_rindex",
          "__builtin_ilogbf128", "__builtin_subc", "__builtin_ia32_pmulhw",
          "__builtin_tanhf", "__builtin_copysignf16", "__builtin_mempcpy",
          "__builtin_subcs", "__builtin_strrchr", "__builtin_fprintf",
          "__builtin_ia32_pand", "__builtin_ctanhl", "__builtin_ia32_pslldi",
          "__builtin_sub_overflow", "__builtin_acoshf128", "__builtin_cpowf",
          "__builtin_sqrtl", "__builtin_parity", "__builtin_cosl",
          "__builtin_remainderf", "__builtin_char_memchr",
          "__builtin_ia32_psrlq", "__builtin_acosl", "__builtin_log2l",
          "__builtin_conjl", "__builtin_clz", "__builtin_add_overflow",
          "__builtin_log10", "__builtin___strcat_chk", "__builtin_cprojl",
          "__builtin_copysignf", "__builtin_modff", "__builtin_realloc",
          "__builtin_logf16", "__builtin_expm1f128", "__builtin_nanf128",
          "__builtin_cacoshl", "__builtin_frexp", "__builtin_acosf",
          "__builtin_sinhl", "__builtin___stpcpy_chk",
          "__builtin_is_aligned", "__builtin_dwarf_cfa",
          "__builtin_ia32_packuswb", "__builtin_ia32_psraw",
          "__builtin_casinhl", "__builtin_nexttowardl", "__builtin_va_start",
          "__builtin_scalbln", "__builtin_bswap16", "__builtin_wcslen",
          "__builtin_log10f16", "__builtin_init_dwarf_reg_size_table",
          "__builtin_ctz", "__builtin_strpbrk", "__builtin_strcpy",
          "__builtin_next_arg", "__builtin_sinf16",
          "__builtin_umull_overflow", "__builtin_scalbnf128",
          "__builtin_ia32_pandn", "__builtin_log10f", "__builtin_fmodf16",
          "__builtin_csinh", "__builtin_floorf",
          "__builtin_matrix_transpose", "__builtin_ia32_pcmpeqw",
          "__builtin___get_unsafe_stack_top", "__builtin_log2f",
          "__builtin_wmemchr", "__builtin_ia32_subps", "__builtin_scalblnf",
          "__builtin_fmal", "__builtin_ia32_punpckhwd", "__builtin_parityll",
          "__builtin_va_end", "__builtin_bzero", "__builtin_strncmp",
          "__builtin_fminl", "__builtin_ia32_psradi",
          "__builtin_ssubll_overflow", "__builtin_sqrtf16",
          "__builtin_smull_overflow", "__builtin___vsprintf_chk",
          "__builtin_nansf128", "__builtin_lgammal", "__builtin_nans",
          "__builtin_ceilf16", "__builtin_exp", "__builtin_acosf128",
          "__builtin_rintf16", "__builtin_ia32_paddusw", "__builtin_wmemcmp",
          "__builtin_round", "__builtin_hypot", "__builtin_subcb",
          "__builtin___strlcpy_chk", "__builtin_csqrt", "__builtin_powif",
          "__builtin_log10l", "__builtin_log10f128", "__builtin_erff128",
          "__builtin_addcl", "__builtin_return_address", "__builtin_fabsf",
          "__builtin_ctanh", "__builtin_ctan", "__builtin_cbrtf128",
          "__builtin_atanhf", "__builtin_ia32_paddusb128", "__builtin_free",
          "__builtin_object_size", "__builtin_va_arg_pack_len",
          "__builtin_tanl", "__builtin_shufflevector", "__builtin_csinhl",
          "__builtin_stpcpy", "__builtin_eh_return_data_regno",
          "__builtin_cexpl", "__builtin_sinl", "__builtin_uaddll_overflow",
          "__builtin_rotateleft16", "__builtin_powf16",
          "__builtin_convertvector", "__builtin_sinhf", "__builtin_hypotl",
          "__builtin_ia32_stmxcsr", "__builtin_bswap64",
          "__builtin_objc_memmove_collectable", "__builtin_ia32_mulps",
          "__builtin_tan", "__builtin_llabs", "__builtin_inff",
          "__builtin_umul_overflow", "__builtin_fmax", "__builtin_erf",
          "__builtin_clzl", "__builtin_ia32_paddq", "__builtin_cosf16",
          "__builtin_tgammal", "__builtin_atan", "__builtin___fprintf_chk",
          "__builtin_wmemcpy", "__builtin_llrintf128", "__builtin_casin",
          "__builtin_logbf128", "__builtin_ctanf", "__builtin_ffsll",
          "__builtin_ia32_pshufw", "__builtin_logf128", "__builtin_index",
          "__builtin_ccosl", "__builtin_abort", "__builtin_powi",
          "__builtin_canonicalize", "__builtin_ia32_psllqi",
          "__builtin_strchr", "__builtin_logb", "__builtin_expf128",
          "__builtin_cimagf", "__builtin_creall", "__builtin_atanh",
          "__builtin_frexpl", "__builtin_exp2f128", "__builtin_csinf",
          "__builtin_ia32_psubusb", "__builtin_ia32_paddsb",
          "__builtin_creal", "__builtin_logl", "__builtin_remquo",
          "__builtin_fmaxl", "__builtin_ia32_cvtsi642ss",
          "__builtin_prefetch", "__builtin_nansl", "__builtin_erfc",
          "__builtin_ccoshl", "__builtin_ia32_emms", "__builtin_tanh",
          "__builtin_scalblnf128", "__builtin_ia32_psubusw128",
          "__builtin_unreachable", "__builtin_calloc", "__builtin_copysignl",
          "__builtin_llrint", "__builtin_ceil", "__builtin_usub_overflow",
          "__builtin_os_log_format", "__builtin_cproj",
          "__builtin_ia32_packssdw", "__builtin_powil",
          "__builtin_ia32_vec_init_v8qi", "__builtin_expl",
          "__builtin_memchr", "__builtin_ia32_cvttss2si64",
          "__builtin_copysign", "__builtin_addcb", "__builtin_logf",
          "__builtin_operator_delete", "__builtin_isunordered",
          "__builtin_casinf", "__builtin_ia32_cvtss2si64",
          "__builtin_ia32_paddusw128", "__builtin_os_log_format_buffer_size",
          "__builtin_memmove", "__builtin_fmaf", "__builtin_debugtrap",
          "__builtin_dynamic_object_size", "__builtin_ffs",
          "__builtin_usubl_overflow", "__builtin_addcs", "__builtin_cargl",
          "__builtin_tgammaf128", "__builtin_launder",
          "__builtin___memcpy_chk", "__builtin_cpowl",
          "__builtin_remainderf128", "__builtin_ssub_overflow",
          "__builtin_tgamma", "__builtin_matrix_column_major_store",
          "__builtin_strspn", "__builtin_conj", "__builtin_cprojf",
          "__builtin_canonicalizef", "__builtin_lrintl", "__builtin_fmaxf16",
          "__builtin_nan", "__builtin_strstr", "__builtin_expm1f",
          "__builtin___get_unsafe_stack_bottom", "__builtin_ia32_pcmpeqb",
          "__builtin_isnormal", "__builtin_atanl", "__builtin_wcsncmp",
          "__builtin_huge_valf128", "__builtin_clzll", "__builtin_cbrt",
          "__builtin_huge_valf", "__builtin_uadd_overflow",
          "__builtin_copysignf128", "__builtin_truncl",
          "__builtin___stpncpy_chk", "__builtin_ia32_punpckhbw",
          "__builtin_ia32_vec_init_v2si", "__builtin_roundf",
          "__builtin_cimag", "__builtin_ia32_pmaddwd",
          "__builtin___vsnprintf_chk", "__builtin_scalbn",
          "__builtin_lgammaf128", "__builtin_ia32_pcmpgtd", "__builtin_nanf",
          "__builtin_roundl", "__builtin_remainderl",
          "__builtin_saddl_overflow", "__builtin_ceilf128",
          "__builtin_signbitf", "__builtin_tgmath", "__builtin_ceill",
          "__builtin_smul_overflow", "__builtin_cabsl",
          "__builtin_ia32_psrad", "__builtin_fmin", "__builtin_floor",
          "__builtin_scalblnl", "__builtin_atan2f", "__builtin_cacosh",
          "__builtin___strlcat_chk", "__builtin_sinh", "__builtin_ilogbf",
          "__builtin_catanl", "__builtin_ia32_psubsw128", "__builtin_clzs",
          "__builtin_remquof", "__builtin_logbf", "__builtin_fma",
          "__builtin_asinhf128", "__builtin_infl", "__builtin_fminf128",
          "__builtin_bitreverse64", "__builtin_vsprintf",
          "__builtin_remquof128", "__builtin_atanhf128",
          "__builtin___get_unsafe_stack_ptr", "__builtin_signbit",
          "__builtin_lroundf", "__builtin_islessequal", "__builtin_exp2l",
          "__builtin_frame_address", "__builtin_nexttowardf128",
          "__builtin_isinf_sign", "__builtin_inff128", "__builtin_va_copy",
          "__builtin_erfcl", "__builtin_cacosf",
          "__builtin_frob_return_address", "__builtin_vsnprintf",
          "__builtin_sadd_overflow", "__builtin_tanf128",
          "__builtin_rotateleft64", "__builtin_matrix_column_major_load",
          "__builtin_popcountll", "__builtin_nearbyintf", "__builtin_atanf",
          "__builtin_rint", "__builtin_ia32_addps",
          "__builtin_rotateright64", "__builtin_readcyclecounter",
          "__builtin_llroundf", "__builtin_strcspn", "__builtin_asinf",
          "__builtin_lrint", "__builtin_erff", "__builtin_ia32_maxps",
          "__builtin_bcmp", "__builtin_asinf128", "__builtin_rotateleft8",
          "__builtin_ia32_por", "__builtin_nextafterf128", "__builtin_cosh",
          "__builtin_tgammaf", "__builtin_operator_new", "__builtin_crealf",
          "__builtin_longjmp", "__builtin_nextafterf",
          "__builtin_mul_overflow", "__builtin_ia32_psrlwi",
          "__builtin_coshl", "__builtin_ilogb",
          "__builtin_ia32_vec_ext_v8hi", "__builtin_cosf",
          "__builtin_strndup", "__builtin_cpow", "__builtin___mempcpy_chk",
          "__builtin_llrintf", "__builtin_hypotf128", "__builtin_complex",
          "__builtin_remainder", "__builtin_preserve_access_index",
          "__builtin_fmaf128", "__builtin_acosh", "__builtin_sin",
          "__builtin_llround", "__builtin_fabs", "__builtin_trunc",
          "__builtin_fmaxf128", "__builtin_ccosf", "__builtin_acoshl",
          "__builtin___clear_cache", "__builtin_strncasecmp",
          "__builtin_fdiml", "__builtin_ia32_paddw", "__builtin_sinhf128",
          "__builtin_isnan", "__builtin_fdim", "__builtin_isgreaterequal",
          "__builtin_nexttowardf", "__builtin_fminf16",
          "__builtin_ia32_packsswb", "__builtin_sqrt",
          "__builtin_umulll_overflow", "__builtin_floorf16",
          "__builtin_casinh", "__builtin_llrintl", "__builtin_expm1",
          "__builtin_exp2f", "__builtin_fabsl", "__builtin_setjmp",
          "__builtin_nearbyintl", "__builtin_nearbyintf128",
          "__builtin_lrintf", "__builtin_floorl", "__builtin_carg",
          "__builtin_csin", "__builtin_clogl",
          "__builtin_expect_with_probability", "__builtin_erfl",
          "__builtin_asinhl", "__builtin_memcpy", "__builtin_islessgreater",
          "__builtin_ia32_psrlqi", "__builtin_ia32_psubsb",
          "__builtin_ctanhf", "__builtin_wcscmp",
          "__builtin_ia32_psubusb128", "__builtin_bitreverse16",
          "__builtin_classify_type", "__builtin_cacos", "__builtin_lroundl",
          "__builtin_printf", "__builtin_sqrtf", "__builtin_assume",
          "__builtin_rintf", "__builtin_powf", "__builtin_powl",
          "__builtin_cimagl", "__builtin_addcll", "__builtin_ia32_psrlw",
          "__builtin_ia32_pslld", "__builtin_canonicalizef16",
          "__builtin___memccpy_chk", "__builtin_truncf128",
          "__builtin_nextafter", "__builtin_ia32_pxor", "__builtin_strdup",
          "__builtin_fabsf16", "__builtin_strcmp", "__builtin_atanf128",
          "__builtin_ia32_psubsb128", "__builtin_ia32_paddsw128",
          "__builtin_ldexpf", "__builtin_ia32_psrld", "__builtin_truncf16",
          "__builtin___memmove_chk", "__builtin_modff128",
          "__builtin_isfinite", "__builtin_conjf", "__builtin_roundf128",
          "__builtin_powf128", "__builtin_ctzs", "__builtin_roundf16",
          "__builtin_ia32_pcmpgtb", "__builtin_log1pf128",
          "__builtin_rotateright16", "__builtin_alloca",
          "__builtin_ldexpf128", "__builtin_cbrtl", "__builtin_csinhf",
          "__builtin_log2", "__builtin_ia32_paddd", "__builtin_modfl",
          "__builtin_ccos", "__builtin_casinhf", "__builtin_asin",
          "__builtin_erfcf128", "__builtin_clrsbll", "__builtin_ctzl",
          "__builtin_tanhl", "__builtin_saddll_overflow", "__builtin_labs",
          "__builtin_cabsf", "__builtin_ia32_punpckhdq",
          "__builtin_ia32_psubb", "__builtin_rintf128", "__builtin_fdimf",
          "__builtin_ia32_vec_ext_v2si", "__builtin_alloca_with_align",
          "__builtin_wmemmove", "__builtin_ia32_psubsw", "__builtin_strncpy",
          "__builtin_eh_return", "__builtin___memset_chk",
          "__builtin_scalbnf", "__builtin_fpclassify", "__builtin_huge_val",
          "__builtin_ia32_pcmpeqd", "__builtin_frexpf", "__builtin_wcschr",
          "__builtin_truncf", "__builtin_ia32_paddusb",
          "__builtin_canonicalizel", "__builtin_ia32_pcmpgtw",
          "__builtin_fmodl", "__builtin_isinf", "__builtin_ia32_psubq",
          "__builtin_strcat", "__builtin_ilogbl", "__builtin_bitreverse32",
          "__builtin_ceilf", "__builtin_dump_struct", "__builtin_return",
          "__builtin_asinl", "__builtin_frexpf128", "__builtin_ia32_psllwi",
          "__builtin_bitreverse8", "__builtin_va_arg_pack",
          "__builtin___strncpy_chk", "__builtin_nontemporal_store",
          "__builtin_lrintf128", "__builtin_malloc", "__builtin_atanhl",
          "__builtin_uaddl_overflow", "__builtin___strncat_chk",
          "__builtin_flt_rounds", "__builtin_huge_vall", "__builtin_ffsl",
          "__builtin___vprintf_chk", "__builtin_rintl", "__builtin_erfcf",
          "__builtin_ia32_unpcklps", "__builtin_strncat", "__builtin_ctzll",
          "__builtin_stdarg_start", "__builtin_nontemporal_load",
          "__builtin_cbrtf", "__builtin_ia32_pmullw", "__builtin_catan",
          "__builtin_ia32_punpcklbw", "__builtin_nexttoward",
          "__builtin_tanf", "__builtin_rotateright32", "__builtin_exp2",
          "__builtin_log1p", "__builtin_catanf", "__builtin_va_arg",
          "__builtin_expect", "__builtin_subcl", "__builtin_ia32_paddsb128",
          "__builtin___printf_chk", "__builtin_subcll",
          "__builtin___vfprintf_chk", "__builtin_fmod",
          "__builtin_ia32_paddb", "__builtin_call_with_static_chain",
          "__builtin_align_up", "__builtin_lgamma", "__builtin_ccosh",
          "__builtin_sqrtf128", "__builtin_ia32_vec_set_v8hi",
          "__builtin_ldexpl", "__builtin_usubll_overflow",
          "__builtin_sprintf", "__builtin_nearbyint", "__builtin_apply",
          "__builtin_sinf", "__builtin_logbl", "__builtin_log1pl",
          "__builtin_ia32_punpcklwd", "__builtin_asinh",
          "__builtin_constant_p", "__builtin_memcpy_inline",
          "__builtin_fminf", "__builtin_llroundl", "__builtin_csinl",
          "__builtin_ia32_punpckldq", "__builtin_log", "__builtin_expf",
          "__builtin_exp2f16", "__builtin_types_compatible_p",
          "__builtin_atan2l", "__builtin_apply_args", "__builtin_clrsb",
          "__builtin_catanhl", "__builtin___get_unsafe_stack_start",
          "__builtin_ia32_psubusw", "__builtin_llroundf128",
          "__builtin_ctanl", "__builtin_abs", "__builtin_log2f128",
          "__builtin_clogf", "__builtin_strlen", "__builtin_ia32_psubw",
          "__builtin_inf", "__builtin_cosf128", "__builtin_remquol",
          "__builtin_fmaf16", "__builtin_coshf128", "__builtin_cargf",
          "__builtin_acoshf", "__builtin_cacoshf", "__builtin_ia32_psllq",
          "__builtin_trap", "__builtin_smulll_overflow", "__builtin_parityl",
          "__builtin_cacosl", "__builtin_log2f16", "__builtin_annotation",
          "__builtin_clog", "__builtin_varargs_start", "__builtin_fabsf128",
          "__builtin_cexpf", "__builtin_unwind_init", "__builtin_isgreater",
          "__builtin___snprintf_chk", "__builtin_ia32_vec_ext_v4hi",
          "__builtin_cabs", "__builtin_expm1l", "__builtin_coshf",
          "__builtin_casinl", "__builtin_nansf", "__builtin_strcasecmp",
          "__builtin_hypotf", "__builtin_nextafterl", "__builtin_lroundf128",
          "__builtin_csqrtf", "__builtin_catanh", "__builtin_align_down",
          "__builtin_scalbnl", "__builtin_ia32_vec_set_v4hi",
          "__builtin_csqrtl", "__builtin_sinf128", "__builtin_atan2",
          "__builtin_popcountl", "__builtin_ia32_psllw",
          "__builtin___strcpy_chk", "__builtin_atan2f128",
          "__builtin_thread_pointer", "__builtin_addc", "__builtin_cos",
          "__builtin_cexp", "__builtin_memset", "__builtin_nanl",
          "__builtin_popcount", "__builtin_tanhf128", "__builtin_expf16",
          "__builtin_dwarf_sp_column", "__builtin_bcopy", "__builtin_memcmp",
          "__builtin_ccoshf", "__builtin_clrsbl", "__builtin_asinhf",
          "__builtin_floorf128", "__builtin_extend_pointer",
          "__builtin_ia32_ldmxcsr", "__builtin_extract_return_addr",
          "__builtin_bswap32", "__builtin_ldexp", "__builtin_unpredictable",
          "__builtin_fmodf", "__builtin_fmodf128", "__builtin_ia32_psrldi",
          "stdin", "stdout", "stderr", "remove", "rename", "renameat",
          "fclose", "tmpfile", "tmpnam", "tmpnam_r", "tempnam", "fflush",
          "fflush_unlocked", "fopen", "freopen", "fdopen", "fmemopen",
          "open_memstream", "setbuf", "setvbuf", "setbuffer", "setlinebuf",
          "fprintf", "printf", "sprintf", "vfprintf", "vprintf", "vsprintf",
          "snprintf", "vsnprintf", "vdprintf", "dprintf", "fscanf", "scanf",
          "sscanf", "vfscanf", "vscanf", "vsscanf", "fgetc", "getc",
          "getchar", "getc_unlocked", "getchar_unlocked", "fgetc_unlocked",
          "fputc", "putc", "putchar", "fputc_unlocked", "putc_unlocked",
          "putchar_unlocked", "getw", "putw", "fgets", "__getdelim",
          "getdelim", "getline", "fputs", "puts", "ungetc", "fread",
          "fwrite", "fread_unlocked", "fwrite_unlocked", "fseek", "ftell",
          "rewind", "fseeko", "ftello", "fgetpos", "fsetpos", "clearerr",
          "feof", "ferror", "clearerr_unlocked", "feof_unlocked",
          "ferror_unlocked", "perror", "fileno", "fileno_unlocked", "pclose",
          "popen", "ctermid", "flockfile", "ftrylockfile", "funlockfile",
          "__uflow", "__overflow"
        ],
        "New Types": [
          "max_align_t", "__anonstruct_max_align_t_247203726", "wchar_t",
          "ptrdiff_t", "fpos_t", "ssize_t", "off_t", "va_list", "_IO_FILE",
          "_IO_lock_t", "_IO_wide_data", "_IO_codecvt", "_IO_marker", "FILE",
          "__FILE", "_IO_FILE", "__fpos64_t", "_G_fpos64_t", "__fpos_t",
          "_G_fpos_t", "__mbstate_t", "__anonstruct___mbstate_t_968396665",
          "__anonunion___value_751190509", "__sig_atomic_t", "__socklen_t",
          "__intptr_t", "__caddr_t", "__loff_t", "__syscall_ulong_t",
          "__syscall_slong_t", "__ssize_t", "__fsword_t", "__fsfilcnt64_t",
          "__fsfilcnt_t", "__fsblkcnt64_t", "__fsblkcnt_t", "__blkcnt64_t",
          "__blkcnt_t", "__blksize_t", "__timer_t", "__clockid_t", "__key_t",
          "__daddr_t", "__suseconds64_t", "__suseconds_t", "__useconds_t",
          "__time_t", "__id_t", "__rlim64_t", "__rlim_t", "__clock_t",
          "__fsid_t", "__anonstruct___fsid_t_109580352", "__pid_t",
          "__off64_t", "__off_t", "__nlink_t", "__mode_t", "__ino64_t",
          "__ino_t", "__gid_t", "__uid_t", "__dev_t", "__uintmax_t",
          "__intmax_t", "__u_quad_t", "__quad_t", "__uint_least64_t",
          "__int_least64_t", "__uint_least32_t", "__int_least32_t",
          "__uint_least16_t", "__int_least16_t", "__uint_least8_t",
          "__int_least8_t", "__uint64_t", "__int64_t", "__uint32_t",
          "__int32_t", "__uint16_t", "__int16_t", "__uint8_t", "__int8_t",
          "__u_long", "__u_int", "__u_short", "__u_char", "__gnuc_va_list",
          "size_t"
        ]
      }
    }
  ]
}
END-UNIVERSE
*/


/* BEGIN TYPEDEF __fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
typedef struct _G_fpos_t __fpos_t;
/* END TYPEDEF __fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 */

/* BEGIN TYPEDEF FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/FILE.h:7 */
#line 7 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
typedef struct _IO_FILE FILE;
/* END TYPEDEF FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/FILE.h:7 */

/* BEGIN UNION __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
union __anonunion___value_751190509 {
   unsigned int __wch ;
   char __wchb[4] ;
};
/* END UNION __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */

/* BEGIN TYPEDEF __ssize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:194 */
#line 194 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __ssize_t;
/* END TYPEDEF __ssize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:194 */

/* BEGIN TYPEDEF __gnuc_va_list LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h:40 */
#line 40 "/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
/* END TYPEDEF __gnuc_va_list LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h:40 */

/* BEGIN TYPEDEF size_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:209 */
#line 209 "/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h"
typedef unsigned long size_t;
/* END TYPEDEF size_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:209 */

/* BEGIN FUNCTION-DECL __builtin_free LOC=BUILTIN VKEY=286 */
/* compiler builtin: 
   void __builtin_free(void * ) ;  */
/* END FUNCTION-DECL __builtin_free LOC=BUILTIN VKEY=286 */

/* BEGIN TYPEDEF __off_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:152 */
#line 152 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
/* END TYPEDEF __off_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:152 */

/* BEGIN TYPEDEF __uint16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:40 */
#line 40 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned short __uint16_t;
/* END TYPEDEF __uint16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:40 */

/* BEGIN TYPEDEF fpos_t LOC=/usr/include/stdio.h:84 */
#line 84 "/usr/include/stdio.h"
typedef __fpos_t fpos_t;
/* END TYPEDEF fpos_t LOC=/usr/include/stdio.h:84 */

/* BEGIN TYPEDEF __int64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:44 */
#line 44 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __int64_t;
/* END TYPEDEF __int64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:44 */

/* BEGIN FUNCTION-DECL-EXTERN fclose LOC=/usr/include/stdio.h:178 VKEY=996 */
#line 178 "/usr/include/stdio.h"
extern int fclose(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fclose LOC=/usr/include/stdio.h:178 VKEY=996 */

/* BEGIN TYPEDEF __uint8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:38 */
#line 38 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned char __uint8_t;
/* END TYPEDEF __uint8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:38 */

/* BEGIN TYPEDEF __uint32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:42 */
#line 42 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uint32_t;
/* END TYPEDEF __uint32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:42 */

/* BEGIN TYPEDEF __int16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:39 */
#line 39 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef short __int16_t;
/* END TYPEDEF __int16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:39 */

/* BEGIN TYPEDEF __off64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:153 */
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
/* END TYPEDEF __off64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:153 */

/* BEGIN TYPEDEF __int32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:41 */
#line 41 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __int32_t;
/* END TYPEDEF __int32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:41 */

/* BEGIN TYPEDEF __int8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:37 */
#line 37 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef signed char __int8_t;
/* END TYPEDEF __int8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:37 */

/* BEGIN STRUCT __anonstruct___mbstate_t_968396665 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
struct __anonstruct___mbstate_t_968396665 {
   int __count ;
   union __anonunion___value_751190509 __value ;
};
/* END STRUCT __anonstruct___mbstate_t_968396665 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */

/* BEGIN TYPEDEF __mbstate_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
typedef struct __anonstruct___mbstate_t_968396665 __mbstate_t;
/* END TYPEDEF __mbstate_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 */

/* BEGIN FUNCTION-DECL-EXTERN pclose LOC=/usr/include/stdio.h:823 VKEY=1389 */
#line 823 "/usr/include/stdio.h"
extern int pclose(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN pclose LOC=/usr/include/stdio.h:823 VKEY=1389 */

/* BEGIN TYPEDEF __uint64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:45 */
#line 45 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __uint64_t;
/* END TYPEDEF __uint64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:45 */

/* BEGIN TYPEDEF _IO_lock_t LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:43 */
#line 43 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
typedef void _IO_lock_t;
/* END TYPEDEF _IO_lock_t LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:43 */

/* BEGIN TYPEDEF __caddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:204 */
#line 204 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef char *__caddr_t;
/* END TYPEDEF __caddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:204 */

/* BEGIN FUNCTION-DECL-EXTERN sscanf LOC=/usr/include/stdio.h:423 VKEY=1142 */
#line 423 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) sscanf)(char const   * __restrict  __s ,
                                                                             char const   * __restrict  __format 
                                                                             , ...)  __asm__("__isoc99_sscanf")  ;
/* END FUNCTION-DECL-EXTERN sscanf LOC=/usr/include/stdio.h:423 VKEY=1142 */

/* BEGIN TYPEDEF ssize_t LOC=/usr/include/stdio.h:77 */
#line 77 "/usr/include/stdio.h"
typedef __ssize_t ssize_t;
/* END TYPEDEF ssize_t LOC=/usr/include/stdio.h:77 */

/* BEGIN TYPEDEF __fsword_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:192 */
#line 192 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __fsword_t;
/* END TYPEDEF __fsword_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:192 */

/* BEGIN TYPEDEF __gid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:147 */
#line 147 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __gid_t;
/* END TYPEDEF __gid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:147 */

/* BEGIN TYPEDEF __fsid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 */
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef struct __anonstruct___fsid_t_109580352 __fsid_t;
/* END TYPEDEF __fsid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 */

/* BEGIN TYPEDEF __daddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:165 */
#line 165 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __daddr_t;
/* END TYPEDEF __daddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:165 */

/* BEGIN FUNCTION-DECL-EXTERN vfprintf LOC=/usr/include/stdio.h:365 VKEY=1089 */
#line 365 "/usr/include/stdio.h"
extern int vfprintf(FILE * __restrict  __s , char const   * __restrict  __format ,
                    __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vfprintf LOC=/usr/include/stdio.h:365 VKEY=1089 */

/* BEGIN FUNCTION-DECL-EXTERN vsnprintf LOC=/usr/include/stdio.h:382 VKEY=1117 */
#line 382
extern  __attribute__((__nothrow__)) int ( /* format attribute */  vsnprintf)(char * __restrict  __s ,
                                                                              size_t __maxlen ,
                                                                              char const   * __restrict  __format ,
                                                                              __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vsnprintf LOC=/usr/include/stdio.h:382 VKEY=1117 */

/* BEGIN TYPEDEF __blksize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:175 */
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blksize_t;
/* END TYPEDEF __blksize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:175 */

/* BEGIN FUNCTION-DECL-EXTERN getchar_unlocked LOC=/usr/include/stdio.h:528 VKEY=1208 */
#line 528 "/usr/include/stdio.h"
extern int getchar_unlocked(void) ;
/* END FUNCTION-DECL-EXTERN getchar_unlocked LOC=/usr/include/stdio.h:528 VKEY=1208 */

/* BEGIN FUNCTION-DECL-EXTERN tempnam LOC=/usr/include/stdio.h:222 VKEY=1010 */
#line 222
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) tempnam)(char const   *__dir ,
                                                                                char const   *__pfx )  __attribute__((__malloc__(__builtin_free,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN tempnam LOC=/usr/include/stdio.h:222 VKEY=1010 */

/* BEGIN TYPEDEF __mode_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:150 */
#line 150 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
/* END TYPEDEF __mode_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:150 */

/* BEGIN TYPEDEF off_t LOC=/usr/include/stdio.h:63 */
#line 63 "/usr/include/stdio.h"
typedef __off_t off_t;
/* END TYPEDEF off_t LOC=/usr/include/stdio.h:63 */

/* BEGIN TYPEDEF __suseconds64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:163 */
#line 163 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds64_t;
/* END TYPEDEF __suseconds64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:163 */

/* BEGIN TYPEDEF __uint_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:55 */
#line 55 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint16_t __uint_least16_t;
/* END TYPEDEF __uint_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:55 */

/* BEGIN FUNCTION-DECL-EXTERN fsetpos LOC=/usr/include/stdio.h:765 VKEY=1359 */
#line 765 "/usr/include/stdio.h"
extern int fsetpos(FILE *__stream , fpos_t const   *__pos ) ;
/* END FUNCTION-DECL-EXTERN fsetpos LOC=/usr/include/stdio.h:765 VKEY=1359 */

/* BEGIN VARIABLE-DEF _TIG_IZ_6cmB_argv LOC=UNKNOWN VKEY=1438 */
char **_TIG_IZ_6cmB_argv  ;
/* END VARIABLE-DEF _TIG_IZ_6cmB_argv LOC=UNKNOWN VKEY=1438 */

/* BEGIN TYPEDEF __time_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:160 */
#line 160 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
/* END TYPEDEF __time_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:160 */

/* BEGIN FUNCTION-DECL-EXTERN fread_unlocked LOC=/usr/include/stdio.h:702 VKEY=1317 */
#line 702 "/usr/include/stdio.h"
extern size_t fread_unlocked(void * __restrict  __ptr , size_t __size , size_t __n ,
                             FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fread_unlocked LOC=/usr/include/stdio.h:702 VKEY=1317 */

/* BEGIN STRUCT-DECL _IO_wide_data LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:38 17 */
#line 38 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_wide_data ;
/* END STRUCT-DECL _IO_wide_data LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:38 17 */

/* BEGIN FUNCTION-DECL-EXTERN feof LOC=/usr/include/stdio.h:788 VKEY=1365 */
#line 788 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) feof)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN feof LOC=/usr/include/stdio.h:788 VKEY=1365 */

/* BEGIN FUNCTION-DECL-EXTERN putc_unlocked LOC=/usr/include/stdio.h:573 VKEY=1234 */
#line 573
extern int putc_unlocked(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN putc_unlocked LOC=/usr/include/stdio.h:573 VKEY=1234 */

/* BEGIN TYPEDEF __ino_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:148 */
#line 148 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino_t;
/* END TYPEDEF __ino_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:148 */

/* BEGIN TYPEDEF __int_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:58 */
#line 58 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int64_t __int_least64_t;
/* END TYPEDEF __int_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:58 */

/* BEGIN FUNCTION-DECL-EXTERN putc LOC=/usr/include/stdio.h:550 VKEY=1221 */
#line 550 "/usr/include/stdio.h"
extern int putc(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN putc LOC=/usr/include/stdio.h:550 VKEY=1221 */

/* BEGIN STRUCT-DECL _IO_codecvt LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:37 16 */
#line 37 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_codecvt ;
/* END STRUCT-DECL _IO_codecvt LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:37 16 */

/* BEGIN FUNCTION-DECL-EXTERN tmpfile LOC=/usr/include/stdio.h:188 VKEY=999 */
#line 188 "/usr/include/stdio.h"
extern FILE *tmpfile(void)  __attribute__((__malloc__(fclose,1), __malloc__)) ;
/* END FUNCTION-DECL-EXTERN tmpfile LOC=/usr/include/stdio.h:188 VKEY=999 */

/* BEGIN VARIABLE-DECL-EXTERN stdin LOC=/usr/include/stdio.h:143 VKEY=974 */
#line 143
extern FILE *stdin ;
/* END VARIABLE-DECL-EXTERN stdin LOC=/usr/include/stdio.h:143 VKEY=974 */

/* BEGIN FUNCTION-DECL-EXTERN feof_unlocked LOC=/usr/include/stdio.h:795 VKEY=1374 */
#line 795
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) feof_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN feof_unlocked LOC=/usr/include/stdio.h:795 VKEY=1374 */

/* BEGIN STRUCT-DECL _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
struct _G_fpos64_t ;
/* END STRUCT-DECL _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */

/* BEGIN TYPEDEF __uint_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:53 */
#line 53 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint8_t __uint_least8_t;
/* END TYPEDEF __uint_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:53 */

/* BEGIN TYPEDEF __uintmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:73 */
#line 73 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __uintmax_t;
/* END TYPEDEF __uintmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:73 */

/* BEGIN TYPEDEF __clock_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:156 */
#line 156 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __clock_t;
/* END TYPEDEF __clock_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:156 */

/* BEGIN FUNCTION-DECL-EXTERN open_memstream LOC=/usr/include/stdio.h:314 VKEY=1045 */
#line 314 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) FILE *( __attribute__((__leaf__)) open_memstream)(char **__bufloc ,
                                                                                       size_t *__sizeloc )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN open_memstream LOC=/usr/include/stdio.h:314 VKEY=1045 */

/* BEGIN VARIABLE-DECL _TIG_IZ_6cmB_envp LOC=UNKNOWN VKEY=1440 */
char **_TIG_IZ_6cmB_envp ;
/* END VARIABLE-DECL _TIG_IZ_6cmB_envp LOC=UNKNOWN VKEY=1440 */

/* BEGIN FUNCTION-DECL-EXTERN snprintf LOC=/usr/include/stdio.h:378 VKEY=1108 */
#line 378
extern  __attribute__((__nothrow__)) int ( /* format attribute */  snprintf)(char * __restrict  __s ,
                                                                             size_t __maxlen ,
                                                                             char const   * __restrict  __format 
                                                                             , ...) ;
/* END FUNCTION-DECL-EXTERN snprintf LOC=/usr/include/stdio.h:378 VKEY=1108 */

/* BEGIN FUNCTION-DECL-EXTERN __uflow LOC=/usr/include/stdio.h:885 VKEY=1409 */
#line 885
extern int __uflow(FILE * ) ;
/* END FUNCTION-DECL-EXTERN __uflow LOC=/usr/include/stdio.h:885 VKEY=1409 */

/* BEGIN STRUCT-DECL __anonstruct_max_align_t_247203726 LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:415 18 */
#line 415 "/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h"
struct __anonstruct_max_align_t_247203726 ;
/* END STRUCT-DECL __anonstruct_max_align_t_247203726 LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:415 18 */

/* BEGIN TYPEDEF __u_short LOC=/usr/include/x86_64-linux-gnu/bits/types.h:32 */
#line 32 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned short __u_short;
/* END TYPEDEF __u_short LOC=/usr/include/x86_64-linux-gnu/bits/types.h:32 */

/* BEGIN FUNCTION-DECL-EXTERN clearerr_unlocked LOC=/usr/include/stdio.h:794 VKEY=1371 */
#line 794 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) clearerr_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN clearerr_unlocked LOC=/usr/include/stdio.h:794 VKEY=1371 */

/* BEGIN TYPEDEF __u_long LOC=/usr/include/x86_64-linux-gnu/bits/types.h:34 */
#line 34 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __u_long;
/* END TYPEDEF __u_long LOC=/usr/include/x86_64-linux-gnu/bits/types.h:34 */

/* BEGIN TYPEDEF ptrdiff_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:143 */
#line 143 "/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h"
typedef long ptrdiff_t;
/* END TYPEDEF ptrdiff_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:143 */

/* BEGIN TYPEDEF __socklen_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:210 */
#line 210 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __socklen_t;
/* END TYPEDEF __socklen_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:210 */

/* BEGIN FUNCTION-DECL-EXTERN printf LOC=/usr/include/stdio.h:356 VKEY=1077 */
#line 356 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
/* END FUNCTION-DECL-EXTERN printf LOC=/usr/include/stdio.h:356 VKEY=1077 */

/* BEGIN STRUCT-DECL __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
struct __anonstruct___fsid_t_109580352 ;
/* END STRUCT-DECL __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */

/* BEGIN VARIABLE-DECL-EXTERN stderr LOC=/usr/include/stdio.h:145 VKEY=976 */
#line 145 "/usr/include/stdio.h"
extern FILE *stderr ;
/* END VARIABLE-DECL-EXTERN stderr LOC=/usr/include/stdio.h:145 VKEY=976 */

/* BEGIN TYPEDEF __uint_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:57 */
#line 57 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint32_t __uint_least32_t;
/* END TYPEDEF __uint_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:57 */

/* BEGIN TYPEDEF __key_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:166 */
#line 166 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __key_t;
/* END TYPEDEF __key_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:166 */

/* BEGIN FUNCTION-DECL-EXTERN putchar LOC=/usr/include/stdio.h:556 VKEY=1224 */
#line 556 "/usr/include/stdio.h"
extern int putchar(int __c ) ;
/* END FUNCTION-DECL-EXTERN putchar LOC=/usr/include/stdio.h:556 VKEY=1224 */

/* BEGIN TYPEDEF __syscall_slong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:197 */
#line 197 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
/* END TYPEDEF __syscall_slong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:197 */

/* BEGIN TYPEDEF __int_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:54 */
#line 54 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int16_t __int_least16_t;
/* END TYPEDEF __int_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:54 */

/* BEGIN TYPEDEF __quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:63 */
#line 63 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __quad_t;
/* END TYPEDEF __quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:63 */

/* BEGIN FUNCTION-DECL-EXTERN getc_unlocked LOC=/usr/include/stdio.h:527 VKEY=1205 */
#line 527 "/usr/include/stdio.h"
extern int getc_unlocked(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN getc_unlocked LOC=/usr/include/stdio.h:527 VKEY=1205 */

/* BEGIN TYPEDEF __loff_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:203 */
#line 203 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __off64_t __loff_t;
/* END TYPEDEF __loff_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:203 */

/* BEGIN FUNCTION-DECL-EXTERN vsprintf LOC=/usr/include/stdio.h:373 VKEY=1101 */
#line 373 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int vsprintf(char * __restrict  __s , char const   * __restrict  __format ,
                                                  __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vsprintf LOC=/usr/include/stdio.h:373 VKEY=1101 */

/* BEGIN FUNCTION-DECL-EXTERN fseeko LOC=/usr/include/stdio.h:736 VKEY=1346 */
#line 736
extern int fseeko(FILE *__stream , __off_t __off , int __whence ) ;
/* END FUNCTION-DECL-EXTERN fseeko LOC=/usr/include/stdio.h:736 VKEY=1346 */

/* BEGIN FUNCTION-DECL-EXTERN fgetc LOC=/usr/include/stdio.h:513 VKEY=1196 */
#line 513
extern int fgetc(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fgetc LOC=/usr/include/stdio.h:513 VKEY=1196 */

/* BEGIN FUNCTION-DECL-EXTERN fmemopen LOC=/usr/include/stdio.h:308 VKEY=1040 */
#line 308
extern  __attribute__((__nothrow__)) FILE *( __attribute__((__leaf__)) fmemopen)(void *__s ,
                                                                                 size_t __len ,
                                                                                 char const   *__modes )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN fmemopen LOC=/usr/include/stdio.h:308 VKEY=1040 */

/* BEGIN TYPEDEF __int_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:56 */
#line 56 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int32_t __int_least32_t;
/* END TYPEDEF __int_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:56 */

/* BEGIN TYPEDEF __fsfilcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:189 */
#line 189 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsfilcnt64_t;
/* END TYPEDEF __fsfilcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:189 */

/* BEGIN FUNCTION-DECL-EXTERN setvbuf LOC=/usr/include/stdio.h:332 VKEY=1059 */
#line 332 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) setvbuf)(FILE * __restrict  __stream ,
                                                                              char * __restrict  __buf ,
                                                                              int __modes ,
                                                                              size_t __n ) ;
/* END FUNCTION-DECL-EXTERN setvbuf LOC=/usr/include/stdio.h:332 VKEY=1059 */

/* BEGIN FUNCTION-DECL-EXTERN renameat LOC=/usr/include/stdio.h:158 VKEY=993 */
#line 158
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) renameat)(int __oldfd ,
                                                                               char const   *__old ,
                                                                               int __newfd ,
                                                                               char const   *__new ) ;
/* END FUNCTION-DECL-EXTERN renameat LOC=/usr/include/stdio.h:158 VKEY=993 */

/* BEGIN FUNCTION-DECL-EXTERN fwrite LOC=/usr/include/stdio.h:681 VKEY=1308 */
#line 681
extern size_t fwrite(void const   * __restrict  __ptr , size_t __size , size_t __n ,
                     FILE * __restrict  __s ) ;
/* END FUNCTION-DECL-EXTERN fwrite LOC=/usr/include/stdio.h:681 VKEY=1308 */

/* BEGIN FUNCTION-DECL-EXTERN remove LOC=/usr/include/stdio.h:152 VKEY=979 */
#line 152
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) remove)(char const   *__filename ) ;
/* END FUNCTION-DECL-EXTERN remove LOC=/usr/include/stdio.h:152 VKEY=979 */

/* BEGIN VARIABLE-DECL _TIG_IZ_6cmB_argv LOC=UNKNOWN VKEY=1438 */
char **_TIG_IZ_6cmB_argv ;
/* END VARIABLE-DECL _TIG_IZ_6cmB_argv LOC=UNKNOWN VKEY=1438 */

/* BEGIN FUNCTION-DECL-EXTERN fseek LOC=/usr/include/stdio.h:713 VKEY=1333 */
#line 713
extern int fseek(FILE *__stream , long __off , int __whence ) ;
/* END FUNCTION-DECL-EXTERN fseek LOC=/usr/include/stdio.h:713 VKEY=1333 */

/* BEGIN TYPEDEF __int_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:52 */
#line 52 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int8_t __int_least8_t;
/* END TYPEDEF __int_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:52 */

/* BEGIN FUNCTION-DECL-EXTERN freopen LOC=/usr/include/stdio.h:265 VKEY=1028 */
#line 265 "/usr/include/stdio.h"
extern FILE *freopen(char const   * __restrict  __filename , char const   * __restrict  __modes ,
                     FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN freopen LOC=/usr/include/stdio.h:265 VKEY=1028 */

/* BEGIN STRUCT _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
struct _G_fpos64_t {
   __off64_t __pos ;
   __mbstate_t __state ;
};
/* END STRUCT _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */

/* BEGIN TYPEDEF __fsfilcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:188 */
#line 188 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsfilcnt_t;
/* END TYPEDEF __fsfilcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:188 */

/* BEGIN FUNCTION-DECL-EXTERN rewind LOC=/usr/include/stdio.h:723 VKEY=1339 */
#line 723 "/usr/include/stdio.h"
extern void rewind(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN rewind LOC=/usr/include/stdio.h:723 VKEY=1339 */

/* BEGIN FUNCTION-DECL-EXTERN fputs LOC=/usr/include/stdio.h:655 VKEY=1282 */
#line 655
extern int fputs(char const   * __restrict  __s , FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fputs LOC=/usr/include/stdio.h:655 VKEY=1282 */

/* BEGIN FUNCTION-DECL-EXTERN putchar_unlocked LOC=/usr/include/stdio.h:574 VKEY=1237 */
#line 574
extern int putchar_unlocked(int __c ) ;
/* END FUNCTION-DECL-EXTERN putchar_unlocked LOC=/usr/include/stdio.h:574 VKEY=1237 */

/* BEGIN FUNCTION-DECL-EXTERN ungetc LOC=/usr/include/stdio.h:668 VKEY=1290 */
#line 668
extern int ungetc(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ungetc LOC=/usr/include/stdio.h:668 VKEY=1290 */

/* BEGIN TYPEDEF __syscall_ulong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:199 */
#line 199 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __syscall_ulong_t;
/* END TYPEDEF __syscall_ulong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:199 */

/* BEGIN FUNCTION-DECL-EXTERN vfscanf LOC=/usr/include/stdio.h:459 VKEY=1162 */
#line 459 "/usr/include/stdio.h"
extern int ( /* format attribute */  vfscanf)(FILE * __restrict  __s , char const   * __restrict  __format ,
                                              __gnuc_va_list __arg )  __asm__("__isoc99_vfscanf")  ;
/* END FUNCTION-DECL-EXTERN vfscanf LOC=/usr/include/stdio.h:459 VKEY=1162 */

/* BEGIN FUNCTION-DECL-EXTERN fwrite_unlocked LOC=/usr/include/stdio.h:704 VKEY=1326 */
#line 704
extern size_t fwrite_unlocked(void const   * __restrict  __ptr , size_t __size , size_t __n ,
                              FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fwrite_unlocked LOC=/usr/include/stdio.h:704 VKEY=1326 */

/* BEGIN FUNCTION-DECL-EXTERN popen LOC=/usr/include/stdio.h:829 VKEY=1394 */
#line 829
extern FILE *popen(char const   *__command , char const   *__modes )  __attribute__((__malloc__(pclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN popen LOC=/usr/include/stdio.h:829 VKEY=1394 */

/* BEGIN TYPEDEF __rlim_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:157 */
#line 157 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __rlim_t;
/* END TYPEDEF __rlim_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:157 */

/* BEGIN STRUCT __anonstruct_max_align_t_247203726 LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:415 18 */
#line 415 "/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h"
struct __anonstruct_max_align_t_247203726 {
   long long __max_align_ll  __attribute__((__aligned__(__alignof__(long long )))) ;
   long double __max_align_ld  __attribute__((__aligned__(__alignof__(long double )))) ;
};
/* END STRUCT __anonstruct_max_align_t_247203726 LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:415 18 */

/* BEGIN FUNCTION-DECL-EXTERN funlockfile LOC=/usr/include/stdio.h:874 VKEY=1406 */
#line 874 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) funlockfile)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN funlockfile LOC=/usr/include/stdio.h:874 VKEY=1406 */

/* BEGIN TYPEDEF va_list LOC=/usr/include/stdio.h:52 */
#line 52 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
/* END TYPEDEF va_list LOC=/usr/include/stdio.h:52 */

/* BEGIN TYPEDEF __id_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:159 */
#line 159 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __id_t;
/* END TYPEDEF __id_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:159 */

/* BEGIN FUNCTION-DECL-EXTERN rename LOC=/usr/include/stdio.h:154 VKEY=984 */
#line 154 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) rename)(char const   *__old ,
                                                                             char const   *__new ) ;
/* END FUNCTION-DECL-EXTERN rename LOC=/usr/include/stdio.h:154 VKEY=984 */

/* BEGIN FUNCTION-DECL-EXTERN perror LOC=/usr/include/stdio.h:804 VKEY=1380 */
#line 804
extern void perror(char const   *__s ) ;
/* END FUNCTION-DECL-EXTERN perror LOC=/usr/include/stdio.h:804 VKEY=1380 */

/* BEGIN FUNCTION-DECL-EXTERN fputc LOC=/usr/include/stdio.h:549 VKEY=1216 */
#line 549
extern int fputc(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fputc LOC=/usr/include/stdio.h:549 VKEY=1216 */

/* BEGIN FUNCTION-DECL-EXTERN ferror LOC=/usr/include/stdio.h:790 VKEY=1368 */
#line 790
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) ferror)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ferror LOC=/usr/include/stdio.h:790 VKEY=1368 */

/* BEGIN TYPEDEF max_align_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:415 */
#line 415 "/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h"
typedef struct __anonstruct_max_align_t_247203726 max_align_t;
/* END TYPEDEF max_align_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:415 */

/* BEGIN TYPEDEF __uint_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:59 */
#line 59 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint64_t __uint_least64_t;
/* END TYPEDEF __uint_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:59 */

/* BEGIN TYPEDEF __rlim64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:158 */
#line 158 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __rlim64_t;
/* END TYPEDEF __rlim64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:158 */

/* BEGIN TYPEDEF __pid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:154 */
#line 154 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __pid_t;
/* END TYPEDEF __pid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:154 */

/* BEGIN FUNCTION-DECL-EXTERN fdopen LOC=/usr/include/stdio.h:293 VKEY=1033 */
#line 293 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) FILE *( __attribute__((__leaf__)) fdopen)(int __fd ,
                                                                               char const   *__modes )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN fdopen LOC=/usr/include/stdio.h:293 VKEY=1033 */

/* BEGIN FUNCTION-DECL-EXTERN __getdelim LOC=/usr/include/stdio.h:632 VKEY=1261 */
#line 632
extern __ssize_t __getdelim(char ** __restrict  __lineptr , size_t * __restrict  __n ,
                            int __delimiter , FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN __getdelim LOC=/usr/include/stdio.h:632 VKEY=1261 */

/* BEGIN FUNCTION-DECL-EXTERN clearerr LOC=/usr/include/stdio.h:786 VKEY=1362 */
#line 786
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) clearerr)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN clearerr LOC=/usr/include/stdio.h:786 VKEY=1362 */

/* BEGIN FUNCTION-DECL-EXTERN ctermid LOC=/usr/include/stdio.h:837 VKEY=1397 */
#line 837
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) ctermid)(char *__s )  __attribute__((__access__(__write_only__,1))) ;
/* END FUNCTION-DECL-EXTERN ctermid LOC=/usr/include/stdio.h:837 VKEY=1397 */

/* BEGIN FUNCTION-DECL-EXTERN vdprintf LOC=/usr/include/stdio.h:403 VKEY=1124 */
#line 403
extern int ( /* format attribute */  vdprintf)(int __fd , char const   * __restrict  __fmt ,
                                               __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vdprintf LOC=/usr/include/stdio.h:403 VKEY=1124 */

/* BEGIN TYPEDEF __ino64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:149 */
#line 149 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino64_t;
/* END TYPEDEF __ino64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:149 */

/* BEGIN VARIABLE-DEF _TIG_IZ_6cmB_argc LOC=UNKNOWN VKEY=1436 */
int _TIG_IZ_6cmB_argc  ;
/* END VARIABLE-DEF _TIG_IZ_6cmB_argc LOC=UNKNOWN VKEY=1436 */

/* BEGIN TYPEDEF __useconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:161 */
#line 161 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __useconds_t;
/* END TYPEDEF __useconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:161 */

/* BEGIN FUNCTION-DECL-EXTERN vsscanf LOC=/usr/include/stdio.h:471 VKEY=1174 */
#line 471 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( /* format attribute */ __attribute__((__leaf__)) vsscanf)(char const   * __restrict  __s ,
                                                                                                     char const   * __restrict  __format ,
                                                                                                     __gnuc_va_list __arg )  __asm__("__isoc99_vsscanf")  ;
/* END FUNCTION-DECL-EXTERN vsscanf LOC=/usr/include/stdio.h:471 VKEY=1174 */

/* BEGIN TYPEDEF __timer_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:172 */
#line 172 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef void *__timer_t;
/* END TYPEDEF __timer_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:172 */

/* BEGIN FUNCTION-DECL-EXTERN setbuffer LOC=/usr/include/stdio.h:338 VKEY=1066 */
#line 338 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) setbuffer)(FILE * __restrict  __stream ,
                                                                                 char * __restrict  __buf ,
                                                                                 size_t __size ) ;
/* END FUNCTION-DECL-EXTERN setbuffer LOC=/usr/include/stdio.h:338 VKEY=1066 */

/* BEGIN TYPEDEF __FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:5 */
#line 5 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
typedef struct _IO_FILE __FILE;
/* END TYPEDEF __FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:5 */

/* BEGIN FUNCTION-DECL-EXTERN ftell LOC=/usr/include/stdio.h:718 VKEY=1336 */
#line 718 "/usr/include/stdio.h"
extern long ftell(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ftell LOC=/usr/include/stdio.h:718 VKEY=1336 */

/* BEGIN TYPEDEF __dev_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:145 */
#line 145 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __dev_t;
/* END TYPEDEF __dev_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:145 */

/* BEGIN FUNCTION-DECL-EXTERN fscanf LOC=/usr/include/stdio.h:415 VKEY=1134 */
#line 415 "/usr/include/stdio.h"
extern int fscanf(FILE * __restrict  __stream , char const   * __restrict  __format 
                  , ...)  __asm__("__isoc99_fscanf")  ;
/* END FUNCTION-DECL-EXTERN fscanf LOC=/usr/include/stdio.h:415 VKEY=1134 */

/* BEGIN VARIABLE-DECL _TIG_IZ_6cmB_argc LOC=UNKNOWN VKEY=1436 */
int _TIG_IZ_6cmB_argc ;
/* END VARIABLE-DECL _TIG_IZ_6cmB_argc LOC=UNKNOWN VKEY=1436 */

/* BEGIN TYPEDEF __sig_atomic_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:215 */
#line 215 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __sig_atomic_t;
/* END TYPEDEF __sig_atomic_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:215 */

/* BEGIN FUNCTION-DECL-EXTERN vprintf LOC=/usr/include/stdio.h:371 VKEY=1094 */
#line 371 "/usr/include/stdio.h"
extern int vprintf(char const   * __restrict  __format , __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vprintf LOC=/usr/include/stdio.h:371 VKEY=1094 */

/* BEGIN FUNCTION-DECL-EXTERN fgetpos LOC=/usr/include/stdio.h:760 VKEY=1354 */
#line 760
extern int fgetpos(FILE * __restrict  __stream , fpos_t * __restrict  __pos ) ;
/* END FUNCTION-DECL-EXTERN fgetpos LOC=/usr/include/stdio.h:760 VKEY=1354 */

/* BEGIN TYPEDEF __fsblkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:184 */
#line 184 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsblkcnt_t;
/* END TYPEDEF __fsblkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:184 */

/* BEGIN FUNCTION-DECL quick_sort LOC=UNKNOWN VKEY=1447 */
static void quick_sort(int *a , long lo , long hi ) ;
/* END FUNCTION-DECL quick_sort LOC=UNKNOWN VKEY=1447 */

/* BEGIN VARIABLE-DECL-EXTERN stdout LOC=/usr/include/stdio.h:144 VKEY=975 */
#line 144 "/usr/include/stdio.h"
extern FILE *stdout ;
/* END VARIABLE-DECL-EXTERN stdout LOC=/usr/include/stdio.h:144 VKEY=975 */

/* BEGIN FUNCTION-DECL-EXTERN setlinebuf LOC=/usr/include/stdio.h:342 VKEY=1069 */
#line 342
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) setlinebuf)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN setlinebuf LOC=/usr/include/stdio.h:342 VKEY=1069 */

/* BEGIN TYPEDEF __fsblkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:185 */
#line 185 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsblkcnt64_t;
/* END TYPEDEF __fsblkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:185 */

/* BEGIN VARIABLE-DEF _TIG_IZ_6cmB_envp LOC=UNKNOWN VKEY=1440 */
char **_TIG_IZ_6cmB_envp  ;
/* END VARIABLE-DEF _TIG_IZ_6cmB_envp LOC=UNKNOWN VKEY=1440 */

/* BEGIN TYPEDEF __blkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:181 */
#line 181 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt64_t;
/* END TYPEDEF __blkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:181 */

/* BEGIN TYPEDEF __nlink_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:151 */
#line 151 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __nlink_t;
/* END TYPEDEF __nlink_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:151 */

/* BEGIN FUNCTION-DECL-EXTERN fputc_unlocked LOC=/usr/include/stdio.h:565 VKEY=1229 */
#line 565 "/usr/include/stdio.h"
extern int fputc_unlocked(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fputc_unlocked LOC=/usr/include/stdio.h:565 VKEY=1229 */

/* BEGIN FUNCTION-DECL-EXTERN putw LOC=/usr/include/stdio.h:584 VKEY=1245 */
#line 584
extern int putw(int __w , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN putw LOC=/usr/include/stdio.h:584 VKEY=1245 */

/* BEGIN FUNCTION-DECL-EXTERN fflush LOC=/usr/include/stdio.h:230 VKEY=1013 */
#line 230
extern int fflush(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fflush LOC=/usr/include/stdio.h:230 VKEY=1013 */

/* BEGIN FUNCTION-DECL-EXTERN fprintf LOC=/usr/include/stdio.h:350 VKEY=1074 */
#line 350
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
/* END FUNCTION-DECL-EXTERN fprintf LOC=/usr/include/stdio.h:350 VKEY=1074 */

/* BEGIN FUNCTION-DECL-EXTERN ftrylockfile LOC=/usr/include/stdio.h:871 VKEY=1403 */
#line 871
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) ftrylockfile)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ftrylockfile LOC=/usr/include/stdio.h:871 VKEY=1403 */

/* BEGIN FUNCTION-DECL-EXTERN vscanf LOC=/usr/include/stdio.h:467 VKEY=1167 */
#line 467
extern int ( /* format attribute */  vscanf)(char const   * __restrict  __format ,
                                             __gnuc_va_list __arg )  __asm__("__isoc99_vscanf")  ;
/* END FUNCTION-DECL-EXTERN vscanf LOC=/usr/include/stdio.h:467 VKEY=1167 */

/* BEGIN STRUCT-DECL _IO_marker LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:36 15 */
#line 36 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_marker ;
/* END STRUCT-DECL _IO_marker LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:36 15 */

/* BEGIN TYPEDEF __uid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:146 */
#line 146 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uid_t;
/* END TYPEDEF __uid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:146 */

/* BEGIN STRUCT-DECL _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
struct _G_fpos_t ;
/* END STRUCT-DECL _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */

/* BEGIN STRUCT _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:49 14 */
#line 49 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   struct _IO_codecvt *_codecvt ;
   struct _IO_wide_data *_wide_data ;
   struct _IO_FILE *_freeres_list ;
   void *_freeres_buf ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
/* END STRUCT _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:49 14 */

/* BEGIN FUNCTION-DECL-EXTERN getc LOC=/usr/include/stdio.h:514 VKEY=1199 */
#line 514 "/usr/include/stdio.h"
extern int getc(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN getc LOC=/usr/include/stdio.h:514 VKEY=1199 */

/* BEGIN FUNCTION-DECL-EXTERN fileno_unlocked LOC=/usr/include/stdio.h:814 VKEY=1386 */
#line 814
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) fileno_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fileno_unlocked LOC=/usr/include/stdio.h:814 VKEY=1386 */

/* BEGIN TYPEDEF __fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
typedef struct _G_fpos64_t __fpos64_t;
/* END TYPEDEF __fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 */

/* BEGIN FUNCTION-DECL-EXTERN getw LOC=/usr/include/stdio.h:581 VKEY=1240 */
#line 581 "/usr/include/stdio.h"
extern int getw(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN getw LOC=/usr/include/stdio.h:581 VKEY=1240 */

/* BEGIN TYPEDEF __blkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:180 */
#line 180 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt_t;
/* END TYPEDEF __blkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:180 */

/* BEGIN STRUCT-DECL __anonstruct___mbstate_t_968396665 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
struct __anonstruct___mbstate_t_968396665 ;
/* END STRUCT-DECL __anonstruct___mbstate_t_968396665 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */

/* BEGIN TYPEDEF wchar_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:321 */
#line 321 "/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h"
typedef int wchar_t;
/* END TYPEDEF wchar_t LOC=/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h:321 */

/* BEGIN UNION-DECL __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
union __anonunion___value_751190509 ;
/* END UNION-DECL __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */

/* BEGIN FUNCTION-DECL-EXTERN scanf LOC=/usr/include/stdio.h:421 VKEY=1137 */
#line 421 "/usr/include/stdio.h"
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
/* END FUNCTION-DECL-EXTERN scanf LOC=/usr/include/stdio.h:421 VKEY=1137 */

/* BEGIN FUNCTION-DECL-EXTERN puts LOC=/usr/include/stdio.h:661 VKEY=1285 */
#line 661
extern int puts(char const   *__s ) ;
/* END FUNCTION-DECL-EXTERN puts LOC=/usr/include/stdio.h:661 VKEY=1285 */

/* BEGIN TYPEDEF __u_int LOC=/usr/include/x86_64-linux-gnu/bits/types.h:33 */
#line 33 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __u_int;
/* END TYPEDEF __u_int LOC=/usr/include/x86_64-linux-gnu/bits/types.h:33 */

/* BEGIN FUNCTION-DECL-EXTERN getchar LOC=/usr/include/stdio.h:520 VKEY=1202 */
#line 520 "/usr/include/stdio.h"
extern int getchar(void) ;
/* END FUNCTION-DECL-EXTERN getchar LOC=/usr/include/stdio.h:520 VKEY=1202 */

/* BEGIN FUNCTION-DECL-EXTERN dprintf LOC=/usr/include/stdio.h:406 VKEY=1129 */
#line 406
extern int ( /* format attribute */  dprintf)(int __fd , char const   * __restrict  __fmt 
                                              , ...) ;
/* END FUNCTION-DECL-EXTERN dprintf LOC=/usr/include/stdio.h:406 VKEY=1129 */

/* BEGIN FUNCTION-DECL-EXTERN setbuf LOC=/usr/include/stdio.h:328 VKEY=1050 */
#line 328
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) setbuf)(FILE * __restrict  __stream ,
                                                                              char * __restrict  __buf ) ;
/* END FUNCTION-DECL-EXTERN setbuf LOC=/usr/include/stdio.h:328 VKEY=1050 */

/* BEGIN FUNCTION-DECL-EXTERN fileno LOC=/usr/include/stdio.h:809 VKEY=1383 */
#line 809
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) fileno)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fileno LOC=/usr/include/stdio.h:809 VKEY=1383 */

/* BEGIN TYPEDEF __intptr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:207 */
#line 207 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __intptr_t;
/* END TYPEDEF __intptr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:207 */

/* BEGIN STRUCT _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
struct _G_fpos_t {
   __off_t __pos ;
   __mbstate_t __state ;
};
/* END STRUCT _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */

/* BEGIN FUNCTION-DECL-EXTERN tmpnam_r LOC=/usr/include/stdio.h:210 VKEY=1005 */
#line 210 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) tmpnam_r)(char *__s ) ;
/* END FUNCTION-DECL-EXTERN tmpnam_r LOC=/usr/include/stdio.h:210 VKEY=1005 */

/* BEGIN FUNCTION-DECL-EXTERN flockfile LOC=/usr/include/stdio.h:867 VKEY=1400 */
#line 867
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) flockfile)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN flockfile LOC=/usr/include/stdio.h:867 VKEY=1400 */

/* BEGIN FUNCTION-DECL-EXTERN __overflow LOC=/usr/include/stdio.h:886 VKEY=1414 */
#line 886
extern int __overflow(FILE * , int  ) ;
/* END FUNCTION-DECL-EXTERN __overflow LOC=/usr/include/stdio.h:886 VKEY=1414 */

/* BEGIN STRUCT-DECL _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:4 14 */
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
struct _IO_FILE ;
/* END STRUCT-DECL _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:4 14 */

/* BEGIN TYPEDEF __suseconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:162 */
#line 162 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds_t;
/* END TYPEDEF __suseconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:162 */

/* BEGIN STRUCT __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
struct __anonstruct___fsid_t_109580352 {
   int __val[2] ;
};
/* END STRUCT __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */

/* BEGIN FUNCTION-DECL-EXTERN fopen LOC=/usr/include/stdio.h:258 VKEY=1021 */
#line 258 "/usr/include/stdio.h"
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN fopen LOC=/usr/include/stdio.h:258 VKEY=1021 */

/* BEGIN FUNCTION-DECL-EXTERN fflush_unlocked LOC=/usr/include/stdio.h:239 VKEY=1016 */
#line 239
extern int fflush_unlocked(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fflush_unlocked LOC=/usr/include/stdio.h:239 VKEY=1016 */

/* BEGIN FUNCTION-DECL-EXTERN ferror_unlocked LOC=/usr/include/stdio.h:796 VKEY=1377 */
#line 796
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) ferror_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ferror_unlocked LOC=/usr/include/stdio.h:796 VKEY=1377 */

/* BEGIN FUNCTION-DECL-EXTERN getline LOC=/usr/include/stdio.h:645 VKEY=1277 */
#line 645
extern __ssize_t getline(char ** __restrict  __lineptr , size_t * __restrict  __n ,
                         FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN getline LOC=/usr/include/stdio.h:645 VKEY=1277 */

/* BEGIN FUNCTION-DECL-EXTERN getdelim LOC=/usr/include/stdio.h:635 VKEY=1270 */
#line 635
extern __ssize_t getdelim(char ** __restrict  __lineptr , size_t * __restrict  __n ,
                          int __delimiter , FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN getdelim LOC=/usr/include/stdio.h:635 VKEY=1270 */

/* BEGIN TYPEDEF __clockid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:169 */
#line 169 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __clockid_t;
/* END TYPEDEF __clockid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:169 */

/* BEGIN FUNCTION-DECL-EXTERN tmpnam LOC=/usr/include/stdio.h:205 VKEY=1002 */
#line 205 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) tmpnam)(char * ) ;
/* END FUNCTION-DECL-EXTERN tmpnam LOC=/usr/include/stdio.h:205 VKEY=1002 */

/* BEGIN FUNCTION-DECL main LOC=UNKNOWN VKEY=1431 */
int main(int _TIG_IZ_6cmB_formal_argc , char **_TIG_IZ_6cmB_formal_argv , char **_TIG_IZ_6cmB_formal_envp ) ;
/* END FUNCTION-DECL main LOC=UNKNOWN VKEY=1431 */

/* BEGIN FUNCTION-DECL-EXTERN sprintf LOC=/usr/include/stdio.h:358 VKEY=1082 */
#line 358
extern  __attribute__((__nothrow__)) int sprintf(char * __restrict  __s , char const   * __restrict  __format 
                                                 , ...) ;
/* END FUNCTION-DECL-EXTERN sprintf LOC=/usr/include/stdio.h:358 VKEY=1082 */

/* BEGIN TYPEDEF __u_char LOC=/usr/include/x86_64-linux-gnu/bits/types.h:31 */
#line 31 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned char __u_char;
/* END TYPEDEF __u_char LOC=/usr/include/x86_64-linux-gnu/bits/types.h:31 */

/* BEGIN FUNCTION-DECL-EXTERN fread LOC=/usr/include/stdio.h:675 VKEY=1299 */
#line 675 "/usr/include/stdio.h"
extern size_t fread(void * __restrict  __ptr , size_t __size , size_t __n , FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fread LOC=/usr/include/stdio.h:675 VKEY=1299 */

/* BEGIN TYPEDEF __u_quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:64 */
#line 64 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __u_quad_t;
/* END TYPEDEF __u_quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:64 */

/* BEGIN TYPEDEF __intmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:72 */
#line 72 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __intmax_t;
/* END TYPEDEF __intmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:72 */

/* BEGIN FUNCTION-DECL-EXTERN fgets LOC=/usr/include/stdio.h:592 VKEY=1252 */
#line 592 "/usr/include/stdio.h"
extern char *fgets(char * __restrict  __s , int __n , FILE * __restrict  __stream )  __attribute__((__access__(__write_only__,1,2))) ;
/* END FUNCTION-DECL-EXTERN fgets LOC=/usr/include/stdio.h:592 VKEY=1252 */

/* BEGIN FUNCTION-DECL-EXTERN ftello LOC=/usr/include/stdio.h:741 VKEY=1349 */
#line 741
extern __off_t ftello(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ftello LOC=/usr/include/stdio.h:741 VKEY=1349 */

/* BEGIN FUNCTION-DECL-EXTERN fgetc_unlocked LOC=/usr/include/stdio.h:538 VKEY=1211 */
#line 538
extern int fgetc_unlocked(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fgetc_unlocked LOC=/usr/include/stdio.h:538 VKEY=1211 */

/* BEGIN FUNCTION-DEF quick_sort LOC=UNKNOWN VKEY=1447 */
static void quick_sort(int *a , long lo , long hi ) 
{ 
  long i ;
  long j ;
  int pivot ;
  int t ;

  {
#line 5
  while ((int )(((unsigned long )((lo - hi) ^ ((lo ^ hi) & ((lo - hi) ^ lo))) >> 63UL) & 1L)) {
    {
#line 6 "./original/src/quicksort.c"
    i = lo;
#line 6
    j = hi;
#line 7
    pivot = *(a + (lo + (hi - lo) / 2L));
    }
#line 9
    while (1) {
#line 10
      while (((unsigned int )((*(a + i) & ~ pivot) | (~ (*(a + i) ^ pivot) & (*(a + i) - pivot))) >> 31U) & 1) {
#line 10
        i = ((i ^ ~ 1L) + ((i | 1L) + (i | 1L))) + 1L;
      }
#line 11
      while (pivot < *(a + j)) {
#line 11
        j = (j & ~ 1L) - (~ j & 1L);
      }
#line 12
      if ((int )(((unsigned long )((~ (i ^ j) >> 1L) + (i & ~ j)) >> 63UL) & 1L)) {
        {
#line 13
        t = *(a + i);
#line 13
        *(a + i) = *(a + j);
#line 13
        *(a + j) = t;
#line 14
        i = (i ^ 1L) + ((i & 1L) + (i & 1L));
#line 14
        j = (j + ~ 1L) + 1L;
        }
      }
#line 9
      if (! ((int )(((unsigned long )((~ (i ^ j) >> 1L) + (i & ~ j)) >> 63UL) & 1L))) {
#line 9
        break;
      }
    }
#line 18
    if ((int )(((unsigned long )(((j - lo) - (hi - i)) ^ (((j - lo) ^ (hi - i)) & (((j - lo) - (hi - i)) ^ (j - lo)))) >> 63UL) & 1L)) {
#line 19
      if ((int )(((unsigned long )((lo - j) ^ ((lo ^ j) & ((lo - j) ^ lo))) >> 63UL) & 1L)) {
#line 19
        quick_sort(a, lo, j);
      }
#line 20
      lo = i;
    } else {
#line 22
      if ((int )(((unsigned long )((i - hi) ^ ((i ^ hi) & ((i - hi) ^ i))) >> 63UL) & 1L)) {
#line 22
        quick_sort(a, i, hi);
      }
#line 23
      hi = j;
    }
  }
#line 26
  return;
}
}
/* END FUNCTION-DEF quick_sort LOC=UNKNOWN VKEY=1447 */

/* BEGIN FUNCTION-DEF main LOC=UNKNOWN VKEY=1431 */
int main(int _TIG_IZ_6cmB_formal_argc , char **_TIG_IZ_6cmB_formal_argv , char **_TIG_IZ_6cmB_formal_envp ) 
{ 
  int a[10] ;
  size_t n ;
  size_t k ;

  {
  {
  {
  {
  {
  _TIG_IZ_6cmB_argc = 0;
  goto _TIG_IZ_6cmB_argc__INITINLINE__TIG_IZ_6cmB_argc__INIT;
  }
  _TIG_IZ_6cmB_argc__INITINLINE__TIG_IZ_6cmB_argc__INIT: /* CIL Label */ ;
  }
  {
  {
  _TIG_IZ_6cmB_argv = (char **)0;
  goto _TIG_IZ_6cmB_argv__INITINLINE__TIG_IZ_6cmB_argv__INIT;
  }
  _TIG_IZ_6cmB_argv__INITINLINE__TIG_IZ_6cmB_argv__INIT: /* CIL Label */ ;
  }
  {
  {
  _TIG_IZ_6cmB_envp = (char **)0;
  goto _TIG_IZ_6cmB_envp__INITINLINE__TIG_IZ_6cmB_envp__INIT;
  }
  _TIG_IZ_6cmB_envp__INITINLINE__TIG_IZ_6cmB_envp__INIT: /* CIL Label */ ;
  }
  goto megaInitINLINE_megaInit;
  }
  megaInitINLINE_megaInit: /* CIL Label */ ;
  }
  while (1) {
    __asm__ volatile ("##_ANNOTATION_INITIALREGION_-TIG-IZ-6cmB--0":);
    _TIG_IZ_6cmB_argc = _TIG_IZ_6cmB_formal_argc;
    _TIG_IZ_6cmB_argv = _TIG_IZ_6cmB_formal_argv;
    _TIG_IZ_6cmB_envp = _TIG_IZ_6cmB_formal_envp;
    break;
  }
#line 29
  a[0] = 9;
#line 29
  a[1] = 1;
#line 29
  a[2] = 5;
#line 29
  a[3] = 3;
#line 29
  a[4] = 7;
#line 29
  a[5] = 2;
#line 29
  a[6] = 8;
#line 29
  a[7] = 6;
#line 29
  a[8] = 4;
#line 29
  a[9] = 0;
#line 30
  n = sizeof(a) / sizeof(a[0]);
#line 32
  if (n > 1UL) {
#line 32
    quick_sort(a, 0L, (long )n - 1L);
  }
#line 34
  k = (size_t )0;
#line 34
  while (k < n) {
#line 34
    printf((char const   */* __restrict  */)"%d ", a[k]);
#line 34
    k ++;
  }
#line 35
  printf((char const   */* __restrict  */)"\n");
#line 36
  return (0);
}
}
/* END FUNCTION-DEF main LOC=UNKNOWN VKEY=1431 */
